openapi: 3.1.0
info:
  version: 1.0.0
  title: My contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This application provides functionality to manage contacts and user authentication.
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-ofcq.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/get.yaml
    post:
      $ref: ../swagger/paths/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer